Documentation
loft-sh/terraform-provider-loft pull request #35
Opened 2022-06-02 20:12 UTC by lizardruss

- [x] Update data sources to show names as required (can't import using `generate_name`)

2022-06-03 16:41 UTC, jschalz requested changes
Overall: Super great work!! This is way more helpful than the tf generated docs.

Things I love:
- amount of examples provided
- extra links referring to resources and commands users might have to run
- formats in the field descriptions, like `<cluster>/<name>`
- defaults! defined! and! included! love it!!

Things I'd change:
- for any `*.md` file, the page description should be short and sweet, and the description under the # header can be longer and more descriptive
- for any `*.md` file, please change the k8s idempotency link to "Read more about [kubernetes API standards and idempotency here](idempotency link)." It's easier to read than the link directly pasted in.
- arguments should be put in a separate table format for `required`, `optional` and `read-only`
- I don't know if tf generates this, but the "Number" data type for the data fields should be changed to "Integer" or "Float" or whatever value is acceptable. When I see "Number", I wonder if I can include partials or decimals.
- Be careful with the word "user". "user" can be overloaded as a kind of a role, or as a way to describe a person using Loft's tf provider
- Doublecheck each data field/argument has a period at the end of each sentence
- Doublecheck that `loft` is capitalized where appropriate

2022-06-03 16:41 UTC, jschalz commented on docs/data-sources/space.md
> +  The loft_space data source provides information about an existing Loft space that matches the given cluster and name.
Since this is a duplicate of the description below for `loft_space (Data Source)`, maybe this should be a description of the page itself? Personally I'd do a short and sweet summary like "Provides details for loft_space data source".

2022-06-03 16:41 UTC, jschalz commented on docs/data-sources/space.md
>  <!-- schema generated by tfplugindocs -->
The arguments here are kind of hard to read. I'd put these in `Required`,`Optional`, and `Read-Only` tables with fields for the argument name, expected data types, and descriptions.

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-tables

2022-06-03 16:41 UTC, jschalz commented on docs/data-sources/space.md
> +- `delete_after` (Number) If set to non zero, will tell loft to delete the space after the specified seconds of inactivity.
Should loft be capitalized? 🤔

2022-06-03 16:41 UTC, jschalz commented on docs/data-sources/space.md
> +- `generate_name` (String) Prefix, used by the server, to generate a unique name ONLY IF the `name` field has not been provided. This value will also be combined with a unique suffix. Read more: http
> Read more: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#idempotency

I love the link providing more info! For readability, I'd change it to "Read more about [kubernetes API conventions for idempotency here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#idempotency)."

2022-06-03 16:41 UTC, jschalz commented on docs/data-sources/space.md
> +- `sleep_schedule` (String) Put the space to sleep at certain times. See [crontab.guru](https://crontab.guru/) for valid configurations. This might be useful if you want to set the space sleeping ove
I like the "over the weekend" example!

2022-06-03 16:41 UTC, jschalz commented on docs/data-sources/spaces.md
> +  The loft_spaces data source provides information about all Loft spaces in the given cluster.
Same as in `space.md`, maybe this should be a description of the page itself?

2022-06-03 16:41 UTC, jschalz commented on docs/data-sources/spaces.md
>  ## Schema
Which of these are required/optional/read-only?

2022-06-03 16:41 UTC, jschalz commented on docs/data-sources/virtual_cluster.md
> +  The loft_virtual_cluster data source provides information about an existing virtual cluster that matches the given cluster, namespace, and name.
Same as in space.md, maybe this should be a description of the page itself?

2022-06-03 16:41 UTC, jschalz commented on docs/data-sources/virtual_cluster.md
> +- `generate_name` (String) Prefix, used by the server, to generate a unique name ONLY IF the `name` field has not been provided. This value will also be combined with a unique suffix. Read more: http
Read more: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#idempotency

I love the link providing more info! For readability, I'd change it to "Read more about [kubernetes API conventions for idempotency here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#idempotency)."

2022-06-03 16:41 UTC, jschalz commented on docs/data-sources/virtual_cluster.md
>  - `objects` (String) Objects are Kubernetes style yamls that should get deployed into the virtual cluster
For consistency, this needs a period at the end.

2022-06-03 16:41 UTC, jschalz commented on docs/data-sources/virtual_cluster.md
> +- `id` (String) Unique identifier for this virtual cluster. The format is `<cluster>/<namespace>/<name>`.
I love the example format here!!

2022-06-03 16:41 UTC, jschalz commented on docs/data-sources/virtual_clusters.md
> +  The loft_virtual_clusters data source provides information about all virtual clusters that match the given cluster and namespace.
Same as in space.md, maybe this should be a description of the page itself?

2022-06-03 16:41 UTC, jschalz commented on docs/data-sources/virtual_clusters.md
>  <!-- schema generated by tfplugindocs -->
Which of these are required, optional, or read-only?

2022-06-03 16:41 UTC, jschalz commented on docs/index.md
> +page_title: "Loft Provider"
This is missing the subcategory field.
`subcategory: ""`

2022-06-03 16:41 UTC, jschalz commented on docs/index.md
> +  The Loft Provider provides resources to manage your Loft Spaces and Virtual Clusters using Terraform.
I'd move this description down to under #Loft Provider, and then simplify the page description!

2022-06-03 16:41 UTC, jschalz commented on docs/index.md
> +When you login to Loft using the Loft CLI, a `config.json` file is create locally to store your login access key. By default, this Terraform provider will use this access key to authenticate when man
Good reference with the `loft login` link!

2022-06-03 16:41 UTC, jschalz commented on docs/index.md
>  ### Optional
Readability is still difficult here.

2022-06-03 16:41 UTC, jschalz commented on docs/index.md
> +- `insecure` (Boolean) Allow login into an insecure Loft instance. Defaults to `false`.
I like that you included the defaults for config_path and insecure!

2022-06-03 16:41 UTC, jschalz commented on docs/resources/space.md
> +  The loft_space resource is used to manage a Loft space.
Same as in space.md, maybe this should be a description of the page itself?

2022-06-03 16:41 UTC, jschalz commented on docs/resources/space.md
> +Configure [Sleep Mode](https://loft.sh/docs/spaces/sleep-mode) for the space.
Nice reference for Sleep Mode!

2022-06-03 16:41 UTC, jschalz commented on docs/resources/space.md
>  ### Optional
Similar issue with the other arguments fields: needs to be in tables, hard to read right now

2022-06-03 16:41 UTC, jschalz commented on docs/resources/virtual_cluster.md
> +  The loft_virtual_cluster resource is used to manage a Loft virtual cluster.
Same as in space.md, maybe this should be a description of the page itself?

2022-06-03 16:41 UTC, jschalz commented on docs/resources/virtual_cluster.md
>  ### Required
Please changes these arguments to a table format!

2022-06-03 16:41 UTC, jschalz commented on docs/resources/virtual_cluster.md
> +- `generate_name` (String) Prefix, used by the server, to generate a unique name ONLY IF the `name` field has not been provided. This value will also be combined with a unique suffix. Read more: http
For readability, I'd change it to "Read more about [kubernetes API conventions for idempotency here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#idempotency)."

2022-06-03 16:41 UTC, jschalz commented on docs/resources/virtual_cluster.md
>  - `objects` (String) Objects are Kubernetes style yamls that should get deployed into the virtual cluster
For consistency, this should have a period at the end.

2022-06-03 16:41 UTC, jschalz commented on examples/provider/provider.tf
> +  # Uses the default Loft config location ($HOME/.loft/config.json)
I like this additional comment! Good text!

2022-06-03 16:41 UTC, jschalz commented on examples/resources/loft_space/sleep_after.tf
> +  sleep_after = 3600 # Sleep after 1 hour of inactivity
I would consider adding that the integer represents seconds, but if you think that's clear with the "sleep for 1 hour" comment I'm cool with that. Either-or!

2022-06-03 16:41 UTC, jschalz commented on examples/resources/loft_space/sleep_schedule.tf
> +  sleep_schedule  = "* 18 * * *" # Sleep everyday at 6pm
Good examples!!

2022-06-03 16:41 UTC, jschalz commented on internal/provider/data_source_space.go
> +		Description: "The `loft_space` data source provides information about an existing Loft space that matches the given `cluster` and `name`.",
Lovely description additions!!

2022-06-03 16:41 UTC, jschalz commented on internal/provider/provider.go
> +					Description:  "The Loft user's access key.",
Clarification question: what does "user" mean here? Is it a role?

2022-06-03 16:41 UTC, jschalz commented on internal/provider/virtual_cluster_helper.go
> +			Description:   "Prefix, used by the server, to generate a unique name ONLY IF the `name` field has not been provided. This value will also be combined with a unique suffix. Read more: https://gith
So I know I said to change the idempotency links to a simpler link text before, but I want to keep this one as is. I think it's easier to have a link directly in the description of a field when it's code documentation instead of markdown.

2022-06-03 17:24 UTC, lizardruss commented on internal/provider/virtual_cluster_helper.go
> +			Description:   "Prefix, used by the server, to generate a unique name ONLY IF the `name` field has not been provided. This value will also be combined with a unique suffix. Read more: https://gith
The text here is what gets rendered to markdown. I definitely think it looks better with the link text, and most IDEs will still let you click the link when viewing the markdown in code.

2022-06-03 17:26 UTC, lizardruss commented on internal/provider/provider.go
> +					Description:  "The Loft user's access key.",
Would it be ok to link to https://loft.sh/docs/users/ here, and [likewise](https://loft.sh/docs/users/teams) for teams?

2022-06-03 17:30 UTC, lizardruss commented on docs/data-sources/spaces.md
>  ## Schema
I believe for data sources all properties would be considered read only.

2022-06-03 17:46 UTC, lizardruss commented on docs/data-sources/virtual_clusters.md
>  <!-- schema generated by tfplugindocs -->
For data sources all properties would be read only.

2022-06-03 17:48 UTC, lizardruss commented on docs/data-sources/space.md
>  <!-- schema generated by tfplugindocs -->
FWIW, these get rendered differently in terraform's documentation. Here's an [example](https://registry.terraform.io/providers/paultyng/unifi/latest/docs#schema) of how it would look.

2022-06-04 01:24 UTC, lizardruss commented on examples/resources/loft_space/sleep_after.tf
> +  sleep_after = 3600 # Sleep after 1 hour of inactivity
Switched the format of this field to address the ambiguity around `(Number)` in the docs, and the unit of time for the durations. The new format is a string that includes the units:

```tf
sleep_after = "1h" # Sleep after 1 hour of inactivity
```

This format is well known to terraform users, since it is used to [specify timeouts](https://www.terraform.io/plugin/sdkv2/resources/retries-and-customizable-timeouts)

2022-06-06 14:04 UTC, merged